### ISSUE TITLE
How do you type these characters in-game?

### ISSUE THREAD

**Issue by yichifauzi** [TwistedAsylumMC/bedrock-unicode-characters#2]
How to you copy form game and paste to github i know there was from game file but how do u type in???

**Comment by thebigsmileXD** [comment]
Please try https://www.deepl.com/translator to translate from your language to english - what you tried to say could not be understood

**Comment by yichifauzi** [comment]
Sorry, my English is really bad.

I mean, how am I supposed to type these patterns on a normal keyboard?

**Comment by yichifauzi** [comment]
> Please try https://www.deepl.com/translator to translate from your language to english - what you tried to say could not be understood

I really appreciate you providing this great translation site, and I use google which often leads to misunderstandings of different meanings.

**Comment by GPJmp** [comment]
> Sorry, my English is really bad.
> 
> I mean, how am I supposed to type these patterns on a normal keyboard?
In most windows programs you can just hold the left alt key and type the unicode character id (for example U+E046 = E046 -> convert to decimal = 57414, so you hold alt and type 57414 on the numpad). This doesn't work directly in minecraft though, but you can still copy it

**Comment by yichifauzi** [comment]
@GPJmp  Oh Thanks you one more thing
how about in Android?

**Comment by GPJmp** [comment]
@yichifauzi I don't think there is an easy way to type/copy all of these characters on a phone, but you could use a keyboard with clipboard history and text selection tools (eg Gboard) and copy it from this website

**Comment by yichifauzi** [comment]
i know and i using the Gboard
