### ISSUE TITLE
Is PoCketmINE disabled the features

### ISSUE THREAD

**Issue by TungstenVn** [TwistedAsylumMC/bedrock-unicode-characters#4]
if i type the symbol in chat bar , it will be clear in the message. It's still appear in my offline survival world

**Comment by TungstenVn** [comment]
but why

**Comment by Aericio** [comment]
How am I supposed to know why it doesn't work? This repo has nothing to do with PMMP.

**Comment by thebigsmileXD** [comment]
Works just fine using the latest release, both Android and Windows 10. There would be no reason for it to not work due to PMMP. PMMP has nothing to do with it. Check your plugins.
