### ISSUE TITLE
Noto Sans

### ISSUE THREAD

**Issue by IrineuMC** [TwistedAsylumMC/bedrock-unicode-characters#5]
On the Mineplex (Bedrock Edition) server they use motd in noto sans, how to do this?

![Mineplex - Bedrock Server](https://user-images.githubusercontent.com/68472488/90795230-2cc8cf00-e2e4-11ea-9fbd-f23fb4008d3e.PNG)

**Comment by thebigsmileXD** [comment]
This has nothing to do with this repository.

Actually, partners started using the unicode characters to enforce the Mojangles font. Mojang made Noto Sans the new default.
